### ISSUE TITLE
Incompatible with Lost Cities Squared 

### ISSUE THREAD

**Issue by strubium** [MCUmbrella/ATG-Modified#10]
Lost Cities Squared is a my fork of The Lost Cities that fixing bugs and crashes. I haven't changed anything related to the API, just the modid. 

Its GitHub: https://github.com/strubium/LostCitiesSquared/tree/1.12

**Comment by MCUmbrella** [comment]
ATG relies on modid to identify Lost Cities, and this incompatibility is expected behavior. Changes need to be made on your end.

**Comment by strubium** [comment]
baller
